
//============================
//    Dependencies
//============================       
var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var expressValidator = require('express-validator');
var cookieParser = require('cookie-parser');
var session = require('express-session');
var passport = require('passport');
var localStrategy = require('passport-local').Strategy;
var bodyParser = require('body-parser');
var flash = require('connect-flash');
var expressMessages = require('express-messages');


// var mongo = require('mongodb');
// var mongoose = require('mongoose');
// var db = mongoose.connection;
// var multer = require('multer');


//============================
//    Custom Routes
//============================  
var db = require('./model/db');     
var routes = require('./routes/index');
var users = require('./routes/users');
var posts = require('./routes/posts');


//============================
//    Middleware
//============================       
var app = express();

// app.locals sets a global for you to use throughout views and your app
app.locals.moment = require('moment');

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');

// Handle File Uploads with Multer
// var upload = multer({dest:'./uploads'});

// uncomment after placing your favicon in /public
//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));

// Handle Express Sessions
app.use(session({
	secret: 'secret',
	saveUninitialized: true,
	resave: true
}));

// Passports
app.use(passport.initialize());
app.use(passport.session());

// Validator
app.use(expressValidator({
  errorFormatter: function(param, msg, value) {
      var namespace = param.split('.')
      , root    = namespace.shift()
      , formParam = root;

    while(namespace.length) {
      formParam += '[' + namespace.shift() + ']';
    }
    return {
      param : formParam,
      msg   : msg,
      value : value
    };
  }
}));

// original stuff generated by express
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

// Connect-flash
app.use(flash());

// express-messages
app.use(function (req, res, next) {
  res.locals.messages = expressMessages(req, res);
  next();
});


//============================
//    Set our routes
//============================     

// All path route, used to display navbar
// properly depending on user logged in or not
// this must be placed before other routes
app.get('*', function(req, res, next) {
    res.locals.feuser = req.user || null;
    next();
});

app.use('/', routes);
app.use('/users', users);
app.use('/posts', posts);



//============================
//    Error Handlers
//============================       
// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handlers

// development error handler
// will print stacktrace
if (app.get('env') === 'development') {
  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
      message: err.message,
      error: err
    });
  });
}

// production error handler
// no stacktraces leaked to user
app.use(function(err, req, res, next) {
  res.status(err.status || 500);
  res.render('error', {
    message: err.message,
    error: {}
  });
});


module.exports = app;
